# Generated by Django 5.1.4 on 2025-02-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_last_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstoremodel',
            old_name='catergory',
            new_name='category',
        ),
    ]
